### ISSUE TITLE
Suggestion : Smart playlists handling

### ISSUE THREAD

**Issue by oschwab** [lusum/ampache-xbmc-plugin#1]
Hello ,

Handling smart playlists would be great !

Thanks.

**Comment by lusum** [comment]
I have implemented the 95% of the XML api, but i cannot find now an api for smart playlist, i will search, but if you have some links, post here.

**Comment by lusum** [comment]
closed by error, reopened

**Comment by lusum** [comment]
XML api doesn't support smart playlists, see  [that](https://github.com/ampache/ampache/issues/1487) , when the new version will support this i will add for sure.

**Comment by oschwab** [comment]
OK at the moment my ampache install is broken. Once I'll set it up again, I'll have a look to the API to see if I cannot put its management by myself (after all , smart playlist "seems" to be "only" the result of a generated query instead of using a fixed query like for regular playlist , so it might not be overcomplicated)

**Comment by lusum** [comment]
If you will implement this you can pull the patch to the plugin. I don't know how smart playlists work, so i can suppose something.

**Comment by lusum** [comment]
This is a thing as advanced_search, not documented, but present in php api files

   /**
     * advanced_search
     * Perform an advanced search given passed rules
     * @param array $input
     */

maybe could help?

**Comment by lachlan-00** [comment]
In the current develop playlists will also return smartlists as long as they have a limit set.

I didn't think there should be any reason for them to be separated so nothing on your end should need to change to support this

**Comment by lusum** [comment]
ok, i will check the new search api

**Comment by lusum** [comment]
After a lot of time and work, i have made some conclusions. Implement smart playlist creation in kodi, when we have the web interface, that is much more flexible, is an effort that add very little gain. Now the plugin handles very well smart playlists creates in the server, so, i think that connecting on the server with a browser, create the playlist and listen on kodi should be the best solution. Smart playlist creation is once in a time effort, so connecting via web interface it is the best solution. ( also to test them, a lot of smart playlist give thousands of results that are handled with a lot of difficulty by the plugin and kodi )
