### ISSUE TITLE
move to ampache organization as an official project

### ISSUE THREAD

**Issue by lachlan-00** [lusum/ampache-xbmc-plugin#10]
@vollmerk or @SUTJael or @Afterster

This plugin would be great to add into the official org. would one of you like to fork and make myself and @lusum admins so they can continue their great work!

**Comment by lusum** [comment]
Do you want to add this pulgin to the official ampache repo?

EDIT: btw this plugin works also on nextcloud music streaming that use the same api as ampache, i will have to differentiate the api between the two when i will update to the new ampache api version

**Comment by lachlan-00** [comment]
I think we put it under the Ampache organisation as its own project not in the main Ampache repo. I think it would give it more exposure and help advertise the plugin (and Ampache.)

The nextcloud support for Ampache still works? I can help update that. is it a nextcloud plugin or in the project?

**Comment by lusum** [comment]
I have no objection to put this plugin under the Ampache organisation, i appreciate it.

I think is a music app for owncloud/nextcloud https://github.com/owncloud/music , i used it for testing purposes, but normally i use ampache server

**Comment by lachlan-00** [comment]
I'm only the developer/custodian of the Amapche project so it will have to wait for one of the original owners to approve it and fork it. But they're usually open to bringing in more people and projects

I'll install the music app on my nextcloud and see what i can do with it.

**Comment by lusum** [comment]
Ok. i will port the ampache plugin code to the new api

**Comment by lachlan-00** [comment]
@lusum i hope you accept my offer to move into the ampache organisation and become the maintainer of the official ampache Kodi plugin!

**Comment by lusum** [comment]
So, i will commit the ampache fork and not this fork.
