### ISSUE TITLE
Ratings

### ISSUE THREAD

**Issue by nakinigit** [lusum/ampache-xbmc-plugin#2]
Doesn't seem as though setting ratings (1-5 star)is working. I see the option to do so, but the changes don't get written back to the server.

**Comment by lusum** [comment]
I haven't implemented it, i will try in the next release ( coupled with some little bugfix )

**Comment by lusum** [comment]
I have tested it, ampache doesn't send the preciserating in api ( if i set a vote in the web interface, xml-api send always 0 ) and so it is impossible to set the rating, when the ampache project will complete the api, i will implement it in the plugin.

**Comment by lachlan-00** [comment]
A rate method is available in the api https://github.com/ampache/ampache/wiki/XML-methods

Should be releasing the next ampache stable in Dec

**Comment by lusum** [comment]
Rating is implemented in the plugin, it is not possible to send back information to the server cause xbmc don't notify rating changes.

**Comment by lusum** [comment]
Ok, checked again and implemented for songs ( as it is possible in kodi interface )
