### ISSUE TITLE
Error / Nextcloud Ampache won't play any file

### ISSUE THREAD

**Issue by obel1x** [lusum/ampache-xbmc-plugin#3]
Hi, i am getting the following errors when using Nextcloud/Music-App/Ampache-Server (see beneath).
I think this is the relevant part: AttributeError: 'NoneType' object has no attribute 'group'
Investigating the Output of that URL, i got:
```
<root>
<album id="10908">
<name>'74 Jailbreak</name>
<artist id="13841">AC-DC</artist>
<tracks>5</tracks><rating>0</rating><year>1984</year><disk>1</disk><art/><preciserating>0</preciserating></album>
<album id="6911"><name>40 Greatest Metal Songs (VH1)</name><artist id="13820">+ Sampler</artist><tracks>5</tracks><rating>0</rating><year>2011</year><disk>1</disk><art>https://obel1x.de/owncloud/index.php/apps/music/ampache/server/xml.server.php?action=_get_cover&filter=6911&auth=xxx</art><preciserating>0</preciserating></album>
```

and so on. So there seems to be no group-attribute. Is this an error of the server-side or could this be ignored by kodi?

Complete Error log:
`06:01:02.571 T:140626782070528  NOTICE: llURL https://obel1x.de/owncloud/index.php/apps/music/ampache/server/xml.server.php?action=artist_albums&auth=XXX&limit=5000&offset=0&filter=13841
06:01:02.871 T:140626782070528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/obel1x/.kodi/addons/plugin.audio.ampache/default.py", line 615, in <module>
                                                get_items(object_type="albums",object_id=object_id,object_subtype="artist_albums")
                                              File "/home/obel1x/.kodi/addons/plugin.audio.ampache/default.py", line 452, in get_items
                                                addItem( object_type, mode , elem, useCacheArt)
                                              File "/home/obel1x/.kodi/addons/plugin.audio.ampache/default.py", line 250, in addItem
                                                image = get_art(node)
                                              File "/home/obel1x/.kodi/addons/plugin.audio.ampache/default.py", line 88, in get_art
                                                albumArt = cacheArt(node.findtext("art"))
                                              File "/home/obel1x/.kodi/addons/plugin.audio.ampache/default.py", line 36, in cacheArt
                                                imageNamePng = imageID.group(1) + ".png"
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
06:01:02.941 T:140628835405952   ERROR: GetDirectory - Error getting plugin://plugin.audio.ampache/?mode=2&name=AC-DC&object_id=13841
06:01:02.941 T:140628835405952   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.ampache/?mode=2&name=AC-DC&object_id=13841) failed
06:01:07.216 T:140628835405952   ERROR: Error loading Smart playlist special://masterprofile/PartyMode.xsp (failed to read file)
06:01:08.925 T:140628835405952   ERROR: PARTY MODE MANAGER: Party mode found no matching songs. Aborting.`
Regards, Daniel

**Comment by lusum** [comment]
Nextclound don't send any art image name, so the plugin crashes looking for it.

see ... `<art/>`
 instead of  `<art><![CDATA[url/imagename.jpg]]></art>`

i have to handle this and relase an update.

**Comment by lusum** [comment]
I should have fixed withi this commit:

https://github.com/lusum/ampache-xbmc-plugin/commit/b8e9ae561f4a797f28b9cab25fd434ba5a718338

can you try the development version and tell me if it works?

**Comment by obel1x** [comment]
oh, yes-  works perfectly for me! Good work, keep it up. 
You got Bitcoinaddress to spend some coffee to you? I would donate for that.
Do i have to close this, or will you?

**Comment by lusum** [comment]
Thanks for the feedback, no i haven't a Bitcoinaddress, this project is only an hobby. I will close this bug and i will release the new version after some testing.
