### ISSUE TITLE
first song of album not scrobbling

### ISSUE THREAD

**Issue by sishrad** [lusum/ampache-xbmc-plugin#6]
I have tried with both the LastFM and LibreFM scrobble addons in Kodi. In each case the first track of an album isn't scrobbled. All of the subsequent tracks (from 2 to n) are scrobbled.

XBMC plugin version 0.8.0.1
Ampache 3.9.0
Apache 2.4.10
PHP 7.0.6
mySQL 5.5.62
Kodi 17.6

**Comment by lusum** [comment]
I don't know this configuration ( LastFM scrobble ), i have to test it, some links?

It is related to this plugin or to lastFM scrobbler?

**Comment by lachlan-00** [comment]
@sishrad it would be good if you could test this with some ampache logs.

I'll be releasing the next version of Ampache in December but you can try develop now if you'd like

There is also now a scrobble method in the  ampache develop api

**Comment by lusum** [comment]
I will install the new version in december and i will update this plugin, for now i have mantained the plugin only on stable versions

**Comment by lusum** [comment]
I have no idea what scrobbling is. I think is related to the server, cause this plugin don't send any lastFM requests, so i close this issue.

**Comment by lachlan-00** [comment]
yeah this is a server issue which i think is also closed
