### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by hanspu** [lusum/ampache-xbmc-plugin#7]
I am testing the ampache-xbmc addon on a Raspberry Pi 2 with updated LibreElec. My Server is Ampache on Debian LAMP.
When I browse Artists, the add-on will only show me artists beginning with A. The same for the album view.
Browsing by Artist tag will give more results.
When adding an entire album to the Kodi queue the album will be added twice. This however is not consistent, as sometime it only gets added once. 
I am using username and password from a normal ampache user account.

**Comment by lusum** [comment]
Artist and album list updating is usually slow. Can you post me the result of kodi.log, maybe as attachment or on pastebin?

**Comment by hanspu** [comment]
The first issue, that the add-on will only show artists and albums starting with 'A' seems to be due to a setting in Ampache:
_"Alphabet browsing by default for following library items (album,artist,...)"_ 
If anything is set here, Kodi will only show the first anything starting with the first letter in your catalogue.
As for the second issue; nothing shows up in Kodi logs. I will investigate further, if I can find a pattern to this behavior.
By the way, pagination would be a great plus. Scrolling through a single list of several thousand items can be tedious. But then again, Kodi is not that good with pagination anyway.
So everything said, thank you for a helpful piece of code.

**Comment by lusum** [comment]
Pagination should be a good improvement, when i will figure out how to do it in a useful manner, i will do. Some other features like smart playlist are not implemented in ampache api, so it is difficult to implement them. As far i know, this plugin uses all the possible ampache features.
