### ISSUE TITLE
please come to the ampache repo and file any issues you have with the api/software

### ISSUE THREAD

**Issue by lachlan-00** [lusum/ampache-xbmc-plugin#8]
I'm making a call out to all the xml-api client software devs to come over the the repo and make their issues known.

I'm working on updating Ampache to version 4 and would like feedback on those who use the API to actually tell me what they need to make it better.

So far i've added smart playlists to the playlist calls as well as recording/flagging songs.

Please come by when you can and I hope to make all ampache-related software better for everyone! :)

**Comment by obel1x** [comment]
Is this also Client/and middleware(like Subsonic/Plex/DAAP-API) related, or only the Ampache- API itself?
I would really appreciate having Client-Side tools to manage my library via Ampache- Api (or some of the other APIs, but currently i don't see a good way to do it).

Right now i am managing the collection with external tools, needing to rescan the sources each time to sync the metadata taking lot of time.

**Comment by lachlan-00** [comment]
All of them except Plex. I'm removing that backend.

I do the same thing, lots of extra tools and scripts for managing my library. One of my plans is to make some of the scripts and tools I use to available for others integrated into /bin.

If you have actions you do over SQL or through tools I'd be really happy to extend the API to remove that need.

I'm sure we can do refresh_tags, update_art, etc. There's a lot of room to move.

**Comment by lusum** [comment]
Ok, sorry to be late. This plugin works only on ampache xml-api.

I have to try to manage the collection client-side, maybe only adding rescan sould be possible.

To answer Iachlan-00. i have noted the lack of a working voting management ( stars ) and the lack of possibility to implment smart playlists.

I would like to add this plugin in a repository ( maybe the official kodi repository ), but i need some help with the icon and the submission process.

**Comment by lachlan-00** [comment]
I've added smart playlists into the API for the next version. Just have to smooth out the changes.

Extra API functions for stars would be easy enough too.

I do think adding as an official repo would be a good idea too.

**Comment by lachlan-00** [comment]
Oh, implement smart lists is a good idea too. I'll see what we can add for that.

**Comment by lusum** [comment]
It is possible to update the catalog via xml-api?

**Comment by lachlan-00** [comment]
I don't think it is right now but I can add that for you.

**Comment by lachlan-00** [comment]
Gather art and verify would take too long but I think 
catalog_update($id, 'clean'|'add')
Would be a good start

**Comment by lusum** [comment]
It is a request by  obel1x , i think it is not so difficult to implement. Adding require an upload and i don't think it is a good idea. But updating maybe...

**Comment by lachlan-00** [comment]
Add wouldn't add files, just add the new ones to the Catalog that are already there but not in the library

I wouldn't add uploading I think. This is just the add|clean actions from the Inc file

**Comment by lusum** [comment]
Yes, this kind of think make the catalog management easier. No need to log in the server, only add/cancel the files in the music directory and update via client.

**Comment by lachlan-00** [comment]
I agree. This is a great idea and exactly why I wanted input. Thank you!

**Comment by lachlan-00** [comment]
@lusum  i'm adding the following in my branch now.
```
https://[ampache]/server/xml.server.php?action=catalog_action&task=clean_catalog&catalog=2&auth=[auth]&version=350001
```

Just an initial effort now but the actions are pretty easy to add.
```
     * catalog_action
     * MINIMUM_API_VERSION=400001
     * Kick off a catalog update or clean for the selected catalog
     *
     * $input = array(task    = (string) 'add_to_catalog'|'clean_catalog'
     *                catalog = (int) $catalog_id)
     * @param array $input
```

**Comment by lusum** [comment]
Ok, i will have to update my ampache version. BTW, if you will give an example with the api, it will be easier to implement

**Comment by lachlan-00** [comment]
There are lots of new actions in develop branch and I'm working on documenting them in the wiki for API users now. Hopefully this can be helpful.

**Comment by lusum** [comment]
Ok, when the develop version will be ready i will update the plugin ( i have to update my own ampache server to test these changes )
